// Auto-generated TypeScript types from database schema
// DO NOT EDIT MANUALLY - This file is generated by generate_database_types tool

export interface AdminUsersRow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  username: string;
  password_hash: string;
  role: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type AdminUsersInsert = Omit<AdminUsersRow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type AdminUsersUpdate = Partial<AdminUsersInsert>;

export interface CasesS8B8A8A895Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  title: string;
  description: string | null;
  image_url: string;
  customer_name: string | null;
  project_type: string | null;
  sort_order: number | null;
  is_featured: boolean | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CasesS8B8A8A895Insert = Omit<CasesS8B8A8A895Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type CasesS8B8A8A895Update = Partial<CasesS8B8A8A895Insert>;

export interface CompaniesS8B8A8A895Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  logo_url: string | null;
  banner_url: string | null;
  description: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type CompaniesS8B8A8A895Insert = Omit<CompaniesS8B8A8A895Row, 'id', 'corp_id', 'emp_id', 'is_deleted', 'created_at', 'updated_at'>;
export type CompaniesS8B8A8A895Update = Partial<CompaniesS8B8A8A895Insert>;

export interface NewsS8B8A8A895Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  title: string;
  summary: string | null;
  content: string;
  cover_image: string | null;
  category: string | null;
  author: string | null;
  view_count: number | null;
  is_featured: boolean | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type NewsS8B8A8A895Insert = Omit<NewsS8B8A8A895Row, 'id', 'corp_id', 'emp_id', 'is_deleted', 'created_at', 'updated_at'>;
export type NewsS8B8A8A895Update = Partial<NewsS8B8A8A895Insert>;

export interface ProductsS8B8A8A895Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  description: string | null;
  category: string | null;
  price: number | null;
  images: string[] | null;
  sort_order: number | null;
  is_featured: boolean | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type ProductsS8B8A8A895Insert = Omit<ProductsS8B8A8A895Row, 'id', 'corp_id', 'emp_id', 'is_deleted', 'created_at', 'updated_at'>;
export type ProductsS8B8A8A895Update = Partial<ProductsS8B8A8A895Insert>;

export interface SeoSettingsS8B8A8A895Row {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  page_type: string;
  title: string | null;
  keywords: string | null;
  description: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SeoSettingsS8B8A8A895Insert = Omit<SeoSettingsS8B8A8A895Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SeoSettingsS8B8A8A895Update = Partial<SeoSettingsS8B8A8A895Insert>;
