-- 添加更多联系方式字段到 companies 表
ALTER TABLE public.companies_s_8b8a8a89_5 
ADD COLUMN IF NOT EXISTS contact_person VARCHAR(256),
ADD COLUMN IF NOT EXISTS contact_phone1 VARCHAR(50),
ADD COLUMN IF NOT EXISTS contact_phone2 VARCHAR(50),
ADD COLUMN IF NOT EXISTS contact_phone3 VARCHAR(50),
ADD COLUMN IF NOT EXISTS contact_phone4 VARCHAR(50),
ADD COLUMN IF NOT EXISTS contact_phone5 VARCHAR(50),
ADD COLUMN IF NOT EXISTS wechat VARCHAR(100),
ADD COLUMN IF NOT EXISTS qq VARCHAR(50),
ADD COLUMN IF NOT EXISTS fax VARCHAR(50),
ADD COLUMN IF NOT EXISTS business_hours VARCHAR(256);
